language: node_js
sudo: required
addons:
  chrome: stable
node_js:
  - '8'
git:
  depth: 3
branches:
  - develop
  - master
install:
  - npm install
script:
  - npm run test-once
  - npm run build
after_script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - npm run report-coverage
cache:
  npm: true
  directories:
    - "./node_modules/"
before_deploy:
  - cd dist/packages
deploy:
  provider: npm
  email: laixiangran@163.com
  api_key:
    secure: XUYXzppJ5gTWHAsIiTMjTAsciMVyAuxsoqduLQ/ty9YhvUtYyaKSGmJVtb7c2+eKXrvD9m6rPWgxKmN+U2UMjzh+dYC/uopM/Yvx3GR7LNlui3feP2tjJkNOeVrh22wLPmVpApq3F+Aw0XLi45fH8dmw241H9wtOF7olB1SEX3NhF7wCglcm2SN4ZawcVKwl5uyh+1lOi0QEStGcqKf8Ri/3c5WpB10eqWRngShYb3c5+wIiC0tlmRS8VJJ47ro69Nh/7qGkrrRMdNu2K1c5+dweXBXoOIoMkCatRgqIKzxCskXVq5Xv/TuPVLa1e49OEwj18EfvrqJvmgKTk6NsPOrLw7ifH03oI5PAU8gqtJqXq9AtVmMtM+HbGyjZ6k4F0YNHd/LABYoqjb9lUPdw3vuspYY0DHAzHmE5m1p6Wvcpfpp43WS2J33I/DCN5QbDNUFGGnuMBG99Kv5oB29/aDa26ia7nrN1WFTAm7StiOp8Jhp7dzCQGimgu7j/2IsYnbtWsN4+1fQNHjZDGPH/lI1tEx9AKMTfE4956yTzlj0DIDM9LBGAnrF1Kfwimlb4AjT0lSFm36ZtBo4VscGPG91jFobbvbEhOSG36EAvYSpMeC8Z4GUnEEOxx728jNSTzIDLm1wJQzQqeShfpQT/k8w+QyUJawSuURj5Fsyxk2w=
  skip_cleanup: true
  on:
    branches:
      only: master
